[package]
name = "my_library"
version = "0.1.0"
authors = ["BuRny <gamingburny@gmail.com>"]
edition = "2018"

[lib]
name = "my_library"
crate-type = ["cdylib"]

[dependencies]
cute = "0.3.0"

[dependencies.pyo3]
version = "0.8.3"
features = ["extension-module"]
